# Generated by Django 4.0.6 on 2022-07-05 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cuisions_type', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='restaurants_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reataurant_name', models.CharField(max_length=100)),
                ('Description', models.TextField(blank=True, null=True)),
                ('Location', models.TextField()),
                ('Cuisines', models.TextField()),
                ('veg', models.BooleanField()),
                ('Rating', models.FloatField()),
                ('Timing', models.TimeField()),
                ('Contect_no', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Description', models.TextField()),
                ('Price', models.IntegerField()),
                ('veg', models.BooleanField()),
                ('Cuision_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurantapp.cuisines')),
            ],
        ),
    ]
