# Generated by Django 4.0.6 on 2022-07-05 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants_list',
            name='Contect_no',
            field=models.CharField(max_length=10),
        ),
        migrations.RemoveField(
            model_name='restaurants_list',
            name='Cuisines',
        ),
        migrations.AddField(
            model_name='restaurants_list',
            name='Cuisines',
            field=models.ManyToManyField(to='restaurantapp.cuisines'),
        ),
    ]
