# Generated by Django 4.0.6 on 2022-07-06 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0002_alter_restaurants_list_contect_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurants_list',
            name='Timing',
        ),
    ]
